[Variables]
;Weather
substituteTextLight="Showers Late":"light_rain","Rain / Thunder":"rainy_storm","Scattered T-Storms":"storm","AM Showers":"light_rain","PM Showers":"light_rain","AM Rain":"rainy","PM Rain":"rainy","Showers Early":"light_rain","PM Showers":"light_rain","AM Showers":"light_rain","Light Rain":"light_rain","Clouds Early / Clearing Late":"cloudy","Mostly Clear":"sun_cloud","Mostly cloudy":"cloudy","Mostly Sunny":"sun_cloud","Partly Cloudy":"sun_cloud","Partly Cloudy / Wind":"sun_cloud","Sunny / Wind":"windy","Rain / Wind":"rainy","Showers":"light_rain","Clear / Wind":"windy","Sunny":"sun","Clear":"sun","Rain":"rainy","T-Storms":"storm"
substituteTextDark="Showers Late":"light_rain_dark","Rain / Thunder":"rainy_storm_dark","Scattered T-Storms":"storm_dark","AM Showers":"light_rain_dark","PM Showers":"light_rain_dark","AM Rain":"rainy_dark","PM Rain":"rainy_dark","Showers Early":"light_rain_dark","PM Showers":"light_rain_dark","AM Showers":"light_rain_dark","Light Rain":"light_rain_dark","Clouds Early / Clearing Late":"cloudy_dark","Mostly Clear":"sun_cloud_dark","Mostly cloudy":"cloudy_dark","Mostly Sunny":"sun_cloud_dark","Partly Cloudy":"sun_cloud_dark","Partly Cloudy / Wind":"sun_cloud_dark","Sunny / Wind":"windy_dark","Rain / Wind":"rainy_dark","Showers":"light_rain_dark","Clear / Wind":"windy_dark","Sunny":"sun_dark","Clear":"sun_dark","Rain":"rainy_dark","T-Storms":"storm_dark"
substituteText=#substituteTextLight#
substituteDays="Monday":"Mon","Tuesday":"Tues","Wednesday":"Wed","Thursday":"Thur","Friday":"Fri","Saturday":"Sat","Sunday":"Sun"

weatherCode=UKXX0085:1:UK
Unit=m



;cloudy,foggy,light_rain,rainy,rainy_storm,snow,snowflake,storm,Sunny,Sunny_cloud,windy

;Colors
bgColor=27292b
bgColorDark=1f2022
primaryColor=e12c28
whiteColor=fafafa

;Dimem
width=340
offset_def=160
offset=50

;Hidden_vars
batHidden=0
diskHidden=1
weatherHidden=0

darkIconsOn=0
darkIconsOff=1

weatherOn=1
weatherOff=0

cOn=1
cOff=0

;Mail
GmailUsername=username
GmailPassword=pass

;Icons
binIcon=#@#Images\bin
explorerIcon=#@#Images\explorer
mailIcon=#@#Images\mail
browserIcon=#@#Images\browser

;Disks
Disk_one="C:"
Disk_two="D:"
#Location#=CAXX0301:1:CA
Location=CAXX0301:1:CA
