[Variables]
;Weather
substituteTextLight="PM Showers":"light_rain","AM Showers":"light_rain","Mostly Clear":"sun_cloud","Mostly cloudy":"cloudy","Mostly Sunny":"sun_cloud","Partly Cloudy":"sun_cloud","Partly Cloudy / Wind":"sun_cloud","Sunny / Wind":"windy","Scattered T-Storms":"storm","Showers":"light_rain","Clear / Wind":"windy","Sunny":"sun","Clear":"sun","Rain":"rainy"
substituteTextDark="10":"snow_dark","11":"rainy_dark","12":"rainy_dark","13":"snow_dark","14":"snow_dark","15":"snow_dark","16":"snow_dark","17":"snow_dark","18":"snow_dark","19":"foggy_dark","20":"foggy_dark","21":"foggy_dark","22":"foggy_dark","23":"storm_dark","24":"windy_dark","25":"snowflake_dark","26":"cloudy_dark","27":"cloudy_dark","28":"cloudy_dark","29":"sun_cloud_dark","30":"sun_cloud_dark","31":"sun_cloud_dark","32":"sun_cloud_dark","33":"sun_cloud_dark","34":"sun_cloud_dark","35":"rainy_dark","36":"sun_dark","37":"storm_dark","38":"storm_dark","39":"storm_dark","40":"rainy_dark","41":"snow_dark","42":"snow_dark","43":"snow_dark","44":"sun_cloud_dark","45":"rainy_storm_dark","46":"snow_dark","47":"storm_dark","0":"foggy_dark","1":"storm_dark","2":"windy_dark","3":"storm_dark","4":"storm_dark","5":"rainy_dark","6":"rainy_dark","7":"rainy_dark","8":"snowflake_dark","9":"light_rain_dark"
substituteText=#substituteTextLight#
substituteDays="Monday":"Mon","Tuesday":"Tues","Wednesday":"Wed","Thursday":"Thur","Friday":"Fri","Saturday":"Sat","Sunday":"Sun"
Location=
Unit=m


;cloudy,foggy,light_rain,rainy,rainy_storm,snow,snowflake,storm,sun,sun_cloud,windy

;Colors
bgColor=27292b
bgColorDark=1f2022
primaryColor=e12c28
whiteColor=fafafa

;Dimem
width=340
offset_def=160
offset=50

;Hidden_vars
batHidden=1
diskHidden=0
weatherHidden=0

darkIconsOn=0
darkIconsOff=1

weatherOn=1
weatherOff=0

cOn=1
cOff=0

;Mail
GmailUsername=username
GmailPassword=pass

;Icons
binIcon=#@#Images\bin
explorerIcon=#@#Images\explorer
mailIcon=#@#Images\mail
browserIcon=#@#Images\browser

;Disks
Disk_one="C:"
Disk_two="D:"
