[Variables]
;Weather
substituteTextLight="PM Showers":"light_rain","AM Showers":"light_rain","Mostly Clear":"sun_cloud","Mostly cloudy":"cloudy","Mostly Sunny":"sun_cloud","Partly Cloudy":"sun_cloud","Partly Cloudy / Wind":"sun_cloud","Sunny / Wind":"windy","Scattered T-Storms":"storm","Showers":"light_rain","Clear / Wind":"windy","Sunny":"sun","Clear":"sun","Rain":"rainy"
substituteTextDark="PM Showers":"light_rain_dark","AM Showers":"light_rain_dark","Mostly Clear":"sun_cloud_dark","Mostly cloudy":"cloudy_dark","Mostly Sunny":"sun_cloud_dark","Partly Cloudy":"sun_cloud_dark","Partly Cloudy / Wind":"sun_cloud_dark","Sunny / Wind":"windy_dark","Scattered T-Storms":"storm_dark","Showers":"light_rain_dark","Clear / Wind":"windy_dark","Sunny":"sun_dark","Clear":"sun_dark","Rain":"rainy_dark"
substituteText=#substituteTextLight#
substituteDays="Monday":"Mon","Tuesday":"Tues","Wednesday":"Wed","Thursday":"Thur","Friday":"Fri","Saturday":"Sat","Sunday":"Sun"

Location=
Unit=m


;cloudy,foggy,light_rain,rainy,rainy_storm,snow,snowflake,storm,Sunny,Sunny_cloud,windy

;Colors
bgColor=27292b
bgColorDark=1f2022
primaryColor=e12c28
whiteColor=fafafa

;Dimem
width=340
offset_def=160
offset=50

;Hidden_vars
batHidden=0
diskHidden=1
weatherHidden=0

darkIconsOn=0
darkIconsOff=1

weatherOn=1
weatherOff=0

cOn=1
cOff=0

;Mail
GmailUsername=username
GmailPassword=pass

;Icons
binIcon=#@#Images\bin
explorerIcon=#@#Images\explorer
mailIcon=#@#Images\mail
browserIcon=#@#Images\browser

;Disks
Disk_one="C:"
Disk_two="D:"
